locallibrary/catalog/urls.py
from django.urls import path
from . import views 

app_name = "catalog"
urlpatterns = [
  path("", views.index, name="index"),
  path("books/", views.BookListView.as_view(), name="books"),
  path("authors/", views.AuthorListView.as_view(), name="authors"),
  path("book/<int:pk>/", views.BookDetailView.as_view(), name="book_detail"),
  path("author/<int:pk>/", views.AuthorDetailView.as_view(), name="author-detail"),
  path("mybooks/", views.ListBookInstance.as_view(), name='my-borrowed'),
  path("allbooksreserved/", views.ListBookNoReturn.as_view(), name="booksnoreturn"),
  path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]

locallibrary/locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include("catalog.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", RedirectView.as_view(url='/catalog/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibrary/accounts/models.py
from django.db import models

# Create your models here.

locallibrary/catalog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from datetime import date
import uuid

class Genre(models.Model):
    name = models.CharField(max_length=200, help_text='Entre com o genero do livro (ex.: ficção)')

    def __str__(self):
        return self.name

class Book (models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text='entre com uma descrição do livro')
    isbn = models.CharField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='selecione o genero do livro')
    language = models.ForeignKey('Language',on_delete=models.SET_NULL, null=True)

    # author é ForeignKey por que um livro so tera um autor, porem um autor pode ter varios livros de sua autoria
    # já genre e manytomanyfield porque um livro pode possuir varios generos

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('catalog:book_detail', args=[str(self.id)])

    def display_genre(self):
        return ', '.join(genre.name for genre in self.genre.all()[:3])

        display_genre.short_description = 'Genre'


class BookUnstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='id unico para um livro particular')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)


    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "set book as returned"),)

    def __str__(self):
        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)


class Author(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    born_date = models.DateField(null=True, blank=True)
    death_date = models.DateField('Died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def __str__(self):
        return f'{self.first_name}, {self.last_name}'

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

class Language(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

locallibrary/catalog/forms.py
from django import forms
import datetime
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class FormDueBack(forms.Form):
    new_date = forms.DateField(help_text="entre com a nova data para entrega (padrão 3 semanas)")

    def clean_new_date(self):
        data = self.cleaned_data['new_date']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        if data < datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        return data

locallibrary/accounts/views.py
from django.shortcuts import render

# Create your views here.

locallibrary/catalog/views.py
from re import template
from django.shortcuts import render, get_object_or_404
from .models import Book, Author, BookUnstance, Genre, Language
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
# from django import forms
from .forms import FormDueBack
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required, permission_required


def index(request):
  # help(forms.fields)
  num_books = Book.objects.all().count()
  num_intances = BookUnstance.objects.all().count()
  num_intances_available = BookUnstance.objects.filter(status__exact='a').count()
  num_authors = Author.objects.all().count()
  
  num_visitas = request.session.get('num_visitas', 0)
  request.session['num_visitas'] = num_visitas+1

  context = {
    'num_books': num_books,
    "num_instances": num_intances,
    "num_instances_available": num_intances_available,
    "num_authors": num_authors,
    "num_visitas": num_visitas,
  }
  return render(request, "catalog/index.html", context=context)
  
class BookListView(generic.ListView):
  model = Book
  paginate_by = 3
  context_object_name = "livros"
  queryset = Book.objects.all()
  template_name = "catalog/books.html"
  
class BookDetailView(generic.DetailView):
  model = Book

#def books(request):
#  books = Book.objects.all()  
#  return render(request, "catalog/books.html", {
#    "livros": books,
#  })

class AuthorListView(generic.ListView):
  model = Author
  context_object_name = "authors"
  template_name = "catalog/authors.html"

class AuthorDetailView(generic.DetailView):
  model = Author  
  
#def authors(request):
#  autores = Author.objects.all()
#  return render(request, "catalog/authors.html", {
#    "authors": autores,
#  })
  
#def book_detail(request, id):
#  return HttpResponse(f'book id = {id}')

#def author(request, id):
#  return HttpResponse(f'authors id =  {id}')

class ListBookInstance(LoginRequiredMixin, generic.ListView):
  model = BookUnstance
  template_name = "catalog/list_books_instances.html"
  paginate_by = 10

  def get_queryset(self):
    return(
      BookUnstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')
    )

class ListBookNoReturn(PermissionRequiredMixin,LoginRequiredMixin,generic.ListView):
  permission_required = "can_mark_returned"
  model = BookUnstance
  template_name = "catalog/booksnoreturn.html"
  paginate_by = 10

  def get_queryset(self):
      return (
        BookUnstance.objects.filter(status__exact='r')
      )

@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
  book_instance = get_object_or_404(BookUnstance, pk=pk)

  if request.method == "POST":
    form = FormDueBack(request.POST)
    if form.is_valid():
      book_instance.due_back = form.cleaned_data['new_date']
      book_instance.save()
      return HttpResponseRedirect(reverse('catalog:home'))
  else:
    suposta_new_date = datetime.date.today() + datetime.timedelta(weeks=3)
    form = FormDueBack(initial={'new_date': suposta_new_date})
  return render(request, 'catalog/form_renew_book.html', {
    'form': form,
    'book_instace': book_instance,
  })

  

locallibrary/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <ul class="sidebar-nav">
   {% if user.is_authenticated %}
     <li>User: {{ user.get_username }}</li>
     <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
   {% else %}
     <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
   {% endif %}
  </ul>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'catalog:index' %}">Home</a></li>
          <li><a href="{% url 'catalog:books' %}">All books</a></li>
          <li><a href="{% url 'catalog:authors' %}">All authors</a></li>
          <li><a href="{% url 'catalog:my-borrowed' %}">All books instances</a></li>
          <li><a href="{% url 'catalog:booksnoreturn' %}">All books no return </a></li>
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
      {% block pagination %}
        {% if is_paginated %}
          <div class="pagination">
            <span class="page-links">
          {% if page_obj.has_previous %}
            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}
            <span class="page-current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
          {% if page_obj.has_next %}
            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
          {% endif %}
            </span>
        </div>
        {% endif %}
      {% endblock %}
  </div>
</body>
</html>

locallibrary/templates/catalog/author_detail.html
{% extends '../base.html' %}

{% block content%}
    <div>
        <h1>Author: {{ author.last_name }}, {{ author.fist_name }}</h1>
        <p>{{ author.born_date }}</p>
        <div>
            <h2>Books</h2>
            {% for book in author.book_set.all %}
            <div>
                <a href="{% url 'catalog:book_detail' book.pk %}">{{ book.title }}</a>{{ book.count }}
                <p>{{ book.summary }}</p>
            </div>
            {% endfor %}
        </div>
    </div>    
{% endblock %}

locallibrary/templates/catalog/authors.html
{% extends '../base.html' %}

{% block title %}Autores{% endblock %}

{% block content %}
    <h1>Listando Autores</h1>

    {% for autor in authors %}
    <div>          
        <ul>
            <li><a href="{% url 'catalog:author-detail' autor.pk %}">{{ autor.first_name }},{{ autor.first_name }} ({{ autor.born_date }})</a></li>
        </ul>
    </div>
    {% endfor %}
{% endblock %}

locallibrary/templates/catalog/book_detail.html
{% extends "../base.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="{% url 'catalog:author-detail' book.author.pk %}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Language:</strong> {{ book.language }}</p>
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookunstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{copy.due_back}}</p>
        {% if perms.catalog.can_mark_returned %}
          <a href="{% url 'catalog:renew-book-librarian' book.id %}">renew date</a>
        {% endif %}
        {% endif %}
      <p><strong>Imprint:</strong> {{copy.imprint}}</p>
      <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

locallibrary/templates/catalog/books.html
{% extends "../base.html" %}

{% block content %}
  <h1>Book List</h1>
  {% if livros %}
  <ul>
    {% for book in livros %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no books in the library.</p>
  {% endif %}
{% endblock %}

locallibrary/templates/catalog/booksnoreturn.html
{% extends "../base.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookunstance_list %}
    <ul>

      {% for bookinst in bookunstance_list %}
      <li>
        <a href="{% url 'catalog:book_detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

locallibrary/templates/catalog/form_renew_book.html
{% extends '../base.html' %}

{% block content %}
  <h1>Renew: {{ book_instance.book.title }}</h1>
  <p>Borrower: {{ book_instance.borrower }}</p>
  <p {% if book_instance.is_overdue %} class="text-danger"{% endif %} >Due date: {{ book_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

locallibrary/templates/catalog/index.html
{% extends "../base.html" %}

{% block content %}
  <h1>Local Library Home</h1>
  <p>Welcome to LocalLibrary, a website developed by <em>Mozilla Developer Network</em>!</p>
  <h2>Dynamic content</h2>
  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul>

  <p>You have visited this page {{ num_visitas }}{% if num_visitas == 1 %} time{% else %} times{% endif %}.</p>

  <a href="{% url 'login' %}">fazer login</a>
  {% endblock %}

locallibrary/templates/catalog/list_books_instances.html
{% extends "../base.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookunstance_list %}
    <ul>

      {% for bookinst in bookunstance_list %}
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'catalog:book_detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}